name: GreenProtect
main: org.greensky.greenprotect.GreenProtect
version: 0.0.1
commands:
   demo:
      description: This is a demo command.
      usage: /<command> [player]
      permission: <plugin name>.demo
      permission-message: You don't have <permission>
